# Utilities
clean-gradle-wrapper: &clean-gradle-wrapper
  from: gradle-wrapper
  to: .
  excluding:
    - .git
    - .gitignore
    - .gitattributes
    - renovate.json

# Configuration
branch: exercises
packages:
  oop-lab01: &oop01
    format:
      - zip
    destinations:
      - unibo-oop/lab # to publish as a github repository, use "repo". Can be added.
    contents: # content priority grows down the list, higher priority contents overwrite existing files
      - from: java/basics/minimal-proficiency/hello-world
        to: 00-hello-world
      - from: java/basics/minimal-proficiency/analysis-method-scope-with-multifile-compilation
        to: 01-analysis-method-scope-with-multifile-compilation
      - from: java/basics/minimal-proficiency/complete-existing-class-student
        to: 02-fill-class-student
      - from: java/basics/minimal-proficiency/impl-complex-num
        to: 03-impl-complexnum
      - from: java/basics/minimal-proficiency/impl-calculator
        to: 04-impl-calculator
      - from: java/basics/minimal-proficiency/impl-train-with-correlated-fields
        to: 05-train
      - from: java/basics/minimal-proficiency/impl-complex-num-calculator
        to: 06-impl-complexnum-calculator
# NOTE: for the following we need to have explained options of javac (-o, -cp)
#      - from: java/basics/minimal-proficiency/compilation-multifile
#        to: 07-multifile-compilation
  pss-lab01:
    format:
      - zip
    destinations: # Overwrite the destination
      - unibo-lptsi-pss/pss-lab
    contents:
      - from: java/basics/minimal-proficiency/hello-world
        to: 00-hello-world
      - from: java/basics/minimal-proficiency/analysis-method-scope-with-multifile-compilation
        to: 01-scopes
      - from: java/basics/minimal-proficiency/complete-existing-class-student
        to: 02-fill-class-student
      - from: java/basics/minimal-proficiency/impl-calculator
        to: 03-calculator
      - from: java/basics/minimal-proficiency/impl-train-with-correlated-fields
        to: 04-train
      - from: java/basics/minimal-proficiency/compilation-multifile
        to: 05-multifilecompilation
  pss-lab02:
    format:
      - zip
    destinations:
      - unibo-lptsi-pss/pss-lab
    contents:
        # Compilation
      - from: java/basics/minimal-proficiency/compilation-source-folder
        to: 00-compilation-basics
      - from: java/basics/minimal-proficiency/compilation-and-packages
        to: 01-compilation-with-packages
      - from: java/basics/minimal-proficiency/compilation-classpath
        to: 02-compilation-classpath
        # Reference vs. value
      - from: java/basics/minimal-proficiency/reference-value
        to: 03-reference-value
        # Arrays + command line + Gradle
      - from: java/basics/minimal-proficiency/command-line-arguments
        to: 04-program-arguments
        excluding: src
      - from: java/basics/minimal-proficiency/command-line-arguments/src
        to: 04-program-arguments/src/main/java
        excluding: README.md
      - <<: *clean-gradle-wrapper
        to: 04-program-arguments
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 04-program-arguments/build.gradle.kts
        # Constructors + Gradle
      - from: java/basics/minimal-proficiency/constructors/README.md
        to: 05-constructors/README.md
      - from: java/basics/minimal-proficiency/constructors/src
        to: 05-constructors/src/main/java
      - <<: *clean-gradle-wrapper
        to: 05-constructors
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 05-constructors/build.gradle.kts
        # Arrays + Gradle
      - from: java/basics/arrays/array/README.md
        to: 06-array/README.md
      - from: java/basics/arrays/array/src
        to: 06-array/src/main/java
      - <<: *clean-gradle-wrapper
        to: 06-array
      - from: gradle-buildfiles/java-minimal/build.gradle.kts
        to: 06-array
