branch: exercises
packages:
  oop-lab01: &oop01
    format:
      - zip
    destinations:
      - unibo-oop/lab # to publish as a github repository, use "repo". Can be added.
    contents: # content priority grows down the list, higher priority contents overwrite existing files
      - from: java/basics/minimal-proficiency/hello-world
        to: 00-hello-world
      - from: java/basics/minimal-proficiency/scopes
        to: 01-scopes
      - from: java/basics/minimal-proficiency/complete-existing-class
        to: 02-fill-class
      - from: java/basics/minimal-proficiency/calculator
        to: 03-calculator
      - from: java/basics/minimal-proficiency/train
        to: 04-train
  pss-lab01:
    <<: *oop01 # Import from oop01.
    destinations: # Overwrite the destination
      - unibo-lptsi-pss/pss-lab
