name: test-and-deploy
on:
  push:
  pull_request:
  workflow_run:
    workflows: ["branch-synch"]
    types:
      - completed

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v3.5.0
      with:
        distribution: temurin
        java-version: 17
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Tests
      run: ./tests.main.kts
  prepare-deliveries:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.deliveries.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.event.after || master }}
      - id: deliveries
        name: Prepare deliverable packages
        run: ./deployer.main.kts
      - name: Tar files
        run: tar -cvf build.tar build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build.tar
  delivery:
    needs:
      - tests # Don't deliver if testing fails
      - prepare-deliveries
    runs-on: ubuntu-latest
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    concurrency:
      group: delivery-${{ matrix.type }}-${{ matrix.owner }}-${{ matrix.repo }}-${{ matrix.ref }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
      - name: Unpack
        run: tar -xf build.tar
      - name: Deliver an archive
        if: matrix.type == 'zip'
        run: ${{ matrix.type }} to be sent to ${{ matrix.owner }}/${{ matrix.repo }} on release ${{ matrix.ref }} with files ${{ matrix.target }}
      - name: Deliver a branch
        if: matrix.type == 'repo'
        run: ${{ matrix.type }} to be sent to ${{ matrix.owner }}/${{ matrix.repo }} on release ${{ matrix.ref }} with files in ${{ matrix.target }}
