name: test-and-deploy
on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:

jobs:
  tests:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: 
          # - ubuntu
          # - windows
          # - macos
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v3.5.1
      with:
        distribution: temurin
        java-version: 17
    - name: Setup WSL
      if: runner.os == 'Windows'
      uses: Vampire/setup-wsl@v1.3.1
      with:
        distribution: Ubuntu-22.04
    - name: Configure WSL
      if: runner.os == 'Windows'
      shell: wsl-bash {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jre-headless
    - name: Checkout
      uses: actions/checkout@v3.1.0
    - name: Tests
      run: ./tests.main.kts
  prepare-deliveries:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.deliveries.outputs.matrix }}
    steps:
      - name: Compute ref
        id: ref
        run: |
          ruby -e '\
          if "${{ github.event_name }}" == "push" && "${{ github.event.ref }}".end_with?("/master") then
            puts "::set-output name=ref::${{ github.event.after }}"
          else
            puts "::set-output name=ref::master"
          end
          '
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ steps.ref.outputs.ref }}
          submodules: recursive
      - name: Prepare deliverable packages
        id: deliveries
        run: ./deployer.main.kts
      - name: Tar files
        run: tar -cvf build.tar build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build.tar
  delivery:
    needs:
      - tests # Don't deliver if testing fails
      - prepare-deliveries
    runs-on: ubuntu-latest
    if: >-
      !github.event.repository.fork
      && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name == github.repository
      )
    strategy:
      matrix: ${{ fromJSON(needs.prepare-deliveries.outputs.matrix) }}
      max-parallel: 1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: build
      - name: Unpack
        run: tar -xf build.tar
      - name: Deliver an archive
        if: matrix.type == 'release'
        uses: ncipollo/release-action@v1.11.1
        with:
          allowUpdates: true
          artifacts: ${{ matrix.target }}
          owner: ${{ matrix.owner }}
          repo: ${{ matrix.repo }}
          replacesArtifacts: true
          tag: ${{ matrix.ref }}
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Checkout the target repo
        if: matrix.type == 'repo'
        uses: actions/checkout@v3.1.0
        with:
          repository: ${{ matrix.owner }}/${{ matrix.repo }}
          path: target
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Create branches if they do not exist
        if: matrix.type == 'repo'
        working-directory: target
        run: |
          URL="https://${{ secrets.DEPLOYMENT_TOKEN }}@github.com/${{ matrix.owner }}/${{ matrix.repo }}"
          git remote add target $URL
          git fetch target
          git checkout ${{ matrix.ref }} origin/${{ matrix.ref }} || (git checkout -b ${{ matrix.ref }} && git push --set-upstream target ${{ matrix.ref }})
      - name: Deliver a branch
        if: matrix.type == 'repo'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: ${{ matrix.target }}
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          branch: ${{ matrix.ref }}
          repository-name: ${{ matrix.owner }}/${{ matrix.repo }}
